export { default as component } from './component.js'
export { default as stories } from './stories.js'
export { default as styles } from './styles.js'
export { default as testFile } from './testfile.js'
export { default as types } from './types.js'
